//回合阶段
global.PHASE_NULL = 0;
global.PHASE_BEGIN_TURN = 1;
global.PHASE_MAIN_TURN = 2;
global.PHASE_END_TURN = 3;

//客户端与服务端通信函数
global.WC_CONNECTED = 'WC_CONNECTED';
global.CW_LOGIN_REQUEST = 'CW_LOGIN_REQUEST';
global.WC_LOGIN_RESPONSE = 'WC_LOGIN_RESPONSE';
global.CW_ENTERROOM_REQUEST = 'CW_ENTERROOM_REQUEST';
global.WC_ENTERROOM_RESPONSE = 'WC_ENTERROOM_RESPONSE';
global.CW_CHAT_ADD_REQUEST = 'CW_CHAT_ADD_REQUEST';
global.CW_CHAT_ADD_RESPONSE = 'CW_CHAT_ADD_RESPONSE';
